### ISSUE TITLE
This repository needs a license

### ISSUE THREAD

**Issue by hdert** [GsnailG/GsnailG.github.io#15]
You also need the permission of everyone who's contributed to the site, and it's contents, to give consent to the license change. I would recommend doing this before #14's [comment](https://github.com/GsnailG/GsnailG.github.io/issues/14#issuecomment-920567486) is implemented. You can use GitHub's own license recommendations, or you can use a license picker like [this](https://choosealicense.com/) or [this](https://ufal.github.io/public-license-selector/).

**Comment by GsnailG** [comment]
I have the MIT License ready when all parties agree 
@Acrobics has through a personal message
![image](https://user-images.githubusercontent.com/61771862/133566497-31d7ca30-6ef6-427c-815d-e5ec71314cd6.png)
And @hdert too
![image](https://user-images.githubusercontent.com/61771862/133566748-65cb6300-31ab-4a2e-a4e0-41d8ad1b1e2b.png)
![image](https://user-images.githubusercontent.com/61771862/133566861-4b74051c-1cc6-4105-9b13-43cc92c7ce79.png)

Therefore I can (re) create the license page and close this issue when this is done

**Comment by GsnailG** [comment]
### _Done and Dusted!_
