### ISSUE TITLE
Make a standard for what type, and how many underscores are used

### ISSUE THREAD

**Issue by hdert** [GsnailG/GsnailG.github.io#22]
I'm always frustrated when the amount of underscores used differ between cards and sometimes in between cards! I would like to enforce a standard amount of underscores, the standard would be based on the discussions in the comments. I can't think of any alternatives. I've made [this website](https://c.hdert.com) to test different underscore lengths.

**Comment by GsnailG** [comment]
After doing some testing, the standard will now be 7 _ and an update will be made shortly
